### ISSUE TITLE
storyline and country is empty string

### ISSUE THREAD

**Issue by vlahde** [tboothman/imdbphp#266] opened 2021-11-20 08:55 UTC
storyline() and country() is returning an empty string

**Comment by jcvignoli** [comment] 2022-05-02 20:44
I can confirm country() function does not return empty strings. Perhaps could you provide more specific details (IMDB id of the movie/person, how you use IMDBPHP)?

**Comment by duck7000** [comment] 2022-05-02 21:02
for me it is working fine since @vlahde reported it so i don't know if there is a real problem here?

**Comment by miaadp** [comment] 2022-08-03 16:03
I have problem with storyline method
Its return empty string

**Comment by duck7000** [comment] 2022-08-03 20:39
Mm storyline() is indeed not working but i think that is because the data is not loaded from imdb, see this screenshot.
It is a var_dump() from $this->getPage("Title") Storyline data is not loading on my pc

![Screenshot_2022-08-03_22-33-07](https://user-images.githubusercontent.com/15360048/182707161-f84ddab0-80c7-459c-9f6b-a3336bbf0436.png)

So i'm not sure there is something wrong with this method

**Comment by tboothman** [comment] 2022-08-03 21:55
That section (and some others further down) are being fetched after the page loads (possibly after you scroll down a bit) from the graphql api:
![image](https://user-images.githubusercontent.com/1813336/182719284-c82c33c1-b2f4-41fb-8a0c-14bd4b5401fa.png)
![image](https://user-images.githubusercontent.com/1813336/182719348-0d5b6555-36a4-47a7-b456-e747965dfd08.png)

tagline is also broken

**Comment by tboothman** [comment] 2022-08-03 22:06
A minimal request (language/location is possibly important)
curl 'https://caching.graphql.imdb.com/?operationName=TMD_Storyline&variables=%7B%22titleId%22%3A%22tt0306414%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22sha256Hash%22%3A%22cbefc9c4a2dbd0a5583e223e5bc788946016db709a731c85251fc1b1b7a1afbe%22%2C%22version%22%3A1%7D%7D' -H 'content-type: application/json' -H 'x-imdb-user-language: en-GB' -H 'x-imdb-user-country: GB'

The url without escaping:
https://caching.graphql.imdb.com/?operationName=TMD_Storyline&variables={"titleId":"tt0306414"}&extensions={"persistedQuery":{"sha256Hash":"cbefc9c4a2dbd0a5583e223e5bc788946016db709a731c85251fc1b1b7a1afbe","version":1}}
The extensions bit seems important .. but not sure where the hash comes from at the moment.

**Comment by duck7000** [comment] 2022-08-04 09:52
On my pc with adblockers disabled storyline is not loaded anywhere on that page (i use movie 1408 as example)

I didn't change the default language setting of imdbphp so that defaults to US as i remember right? So changing that to GB could help? I will try that.

**Comment by tboothman** [comment] 2023-02-13 20:47
I think this was fixed by https://github.com/tboothman/imdbphp/releases/tag/v7.3.1

**Closed by tboothman** 2023-02-13 20:47 UTC
