### ISSUE TITLE
Seperate the library and the 'website'

### ISSUE THREAD

**Issue by tboothman** [tboothman/imdbphp#25] opened 2015-05-18 16:40 UTC

**Comment by IzzySoft** [comment] 2015-05-19 13:50
Curious to the approach. True, as it is, some people confuse IMDBPHP with a "ready-to-use application" (I've even seen websites setup that way, just having altered some CSS). Maybe moving it to e.g. `demo/` (or even `doc/demo/`), adjusting the links plus `include()`/`require()` statements accordingly?

**Comment by tboothman** [comment] 2015-05-19 16:03
Yea, something like that. I mostly dislike the mix of classes and templates in the same folder. This would only be done as part of 3.0 with a folder rejiggle. If everything else is being moved out of the root maybe this could stay put, but a public or demo folder would be best i think.

**Comment by IzzySoft** [comment] 2015-05-19 19:11
Agreed. Please keep me in the loop here, and give me a little time ahead of "going live" – as a "folder reorg" would also mean adjusting the Makefile (or, if forgotten, an incomplete distribution archive/package :scream_cat:)

**Comment by tboothman** [comment] 2015-05-22 15:58
Need to redo the html, it's embarrassingly poor

**Comment by tboothman** [comment] 2015-05-22 16:00
Add readme to explain what the demo folder is for

**Comment by IzzySoft** [comment] 2015-05-22 19:15
> Need to redo the html, it's embarrassingly poor

That was intended only to demonstrate how to use the API. I kept it "poor on purpose" to keep people from confusing it with a web-app – not that it really seems to have discouraged many …

**Comment by tboothman** [comment] 2015-05-22 23:00
Hah, sorry, I thought someone else had made it :P
The thing is people who know how to use a library won't need it. The only people who might need it for examples are people who are newish to PHP. Giving them an example which is not good quality is not helpful.

**Comment by IzzySoft** [comment] 2015-05-23 20:32
I didn't say I've created it (AFAIR it was already there when I took over the project). I just worte I *kept* it that way :innocent:

**Closed** 2015-06-02 23:07 UTC
