### ISSUE TITLE
Does not get imdb rating

### ISSUE THREAD

**Issue by Thomasdouscha** [tboothman/imdbphp#261] opened 2021-08-31 07:18 UTC
hello,

It does not get imdb rating of [The newsreader]https://www.imdb.com/title/tt13925142/?ref_=tt_rt)

Thanks

**Comment by Thomasdouscha** [comment] 2021-08-31 07:33
For example: rating value = 6.9 get 6 or 7.6 get 7 as it does not get decimal value.

samples:
https://www.imdb.com/title/tt13925142/?ref_=tt_rt
https://www.imdb.com/title/tt12687584/

**Comment by Thomasdouscha** [comment] 2021-08-31 17:09
my website's age 4 years old. https://www.planetdp.org
It was right rating value. Now not. I did not change the code and yes imdbphp last version.
And i will check the code too. May  be it was string in the past. Now decimal. I will check it.

**Comment by Thomasdouscha** [comment] 2021-08-31 17:20
Our code is right. 
get value with this $imdb->rating() and writge to database. Function rating() is not working true.

**Comment by duck7000** [comment] 2021-09-01 09:09
That is really strange, both examples are working perfectly in my app
I use php 7.4, not sure if that has anything to do with it though

![Screenshot from 2021-09-01 10-59-24](https://user-images.githubusercontent.com/15360048/131643998-e4bae8c5-d9c9-4259-8925-79860bf9fcf5.png)
![Screenshot from 2021-09-01 11-00-08](https://user-images.githubusercontent.com/15360048/131644006-6c57e4d4-c26c-4b57-b68e-cefad01f7cb2.png)

First value is a var_dump of rating(), second the actual value in my app.

So imho imdbphp works fine?

Check your output from rating(), if that is ok, then your problem lays in your app

**Comment by Thomasdouscha** [comment] 2021-09-01 16:57
it should be numbers as 7.4 . if return value is "float(7.4)7.4" of course my app can not get the value. It was not like this. for example  7.2 or 6.8 or 4.5. 
But as i told you before it gets value perfectly

**Comment by duck7000** [comment] 2021-09-01 17:34
Relax and read above
> float(7.4)7.4
This is off course not the value, i put var_dump inside the rating value which output float(7.4). the 7.4 behind that is the real output value.

So your output from var_dump inside rating() method give the same output as mine? If so your problem lies not in imdbphp
Can you try that first?
You have systematically search for the problem, so start by checking the output of method rating()

**Comment by Thomasdouscha** [comment] 2021-09-01 17:53
Our app code four years same and it was working perfect. What did you change and why so now i dont know. I am ill 2-3 ddays later i will try to understand your new release.

**Comment by duck7000** [comment] 2021-09-01 19:34
For the record i did not make any changes to this method.
I'm only trying to help you.

**Comment by Thomasdouscha** [comment] 2021-09-01 21:08
I see thanks for trying to help me. That is a very kind of you!
But if you didnot change anything for result it would work. I think data type or something different. But i can check after three days.
And in that time i need to have your helping. If you will be available of course!

Thanks

**Comment by Thomasdouscha** [comment] 2021-09-04 08:11
my code what get rating is was "$ratv = $imdb->rating();" and working perfectly before. Now it cannot get decimal value, just integer. Because i record it to varchar column of mysql.
i changed to code "$ratv = strval($imdb->rating());" now it working very well. That means is changed type of value of rating. my issue resolved now. But i think it is not good to change type of vale.

**Comment by duck7000** [comment] 2021-09-04 09:37
Mm i see what you mean, in version 6.0.0 rating value is string, in later versions rating method is changed and apparently the output is also changed to float.
@tboothman , @jreklund is this something to discuss?

I think the problem is that you save the value as string in your database, i save it as double and have no problems.

It is remarkable that version 6.0.0 was released 26 feb 2018 and nobody complaint, including you? How come you didn't notice this before than? I mean it is 4 years after that release..

**Comment by tboothman** [comment] 2021-09-04 10:32
I haven't written PHP day to day for a while now but PHP never used to care at all about the distinction between stringy numbers and numbers. Seems strange that any standard php code could take a float and turn it into a string and drop the decimal part of it.
Still, representing a number using a numeric type seems like the correct thing to do.

Just having a play around it's very difficult to make the decimal places go away

```php
php > $r = 6.5;
php > var_export("$r");
'6.5'
php > var_export($r);
6.5
php > var_export("".$r);
'6.5'
php > var_export(strval($r));
'6.5'
php > var_export((int)$r);
6
php > var_export((float)$r);
6.5
php > var_export(6.5 == '6.5');
true
php > var_export('6.5' + 1);
7.5
php > var_export((string)$r);
'6.5'
```

**Comment by Thomasdouscha** [comment] 2021-09-04 10:40
when you convert the float number to string and return like this and when user get it to save varchar column in mysql, there is no problem. Because you can make math operation in php as float number etc. thatswhy string is better. 

But it doesnot matter how should be? does motter should be same type of value as before , always. Float? for this reason after revising to imdbphp again this type of value should be float! it is important. 

bacuse we are using imdbphp in our web application. Change value of type can side effect issues of code.

**Comment by tboothman** [comment] 2021-09-04 10:57
I agree that the API shouldn't change, and it generally doesn't without a major version change. In this instance nobody noticed because PHP rarely notices the difference between stringy numbers and numbers.
The test for this method, unchanged since 2014 didn't notice:
https://github.com/tboothman/imdbphp/blob/master/tests/TitleTest.php#L332

**Comment by duck7000** [comment] 2021-09-04 14:15
Well i didn't notice this either, i checked old versions to notice that there is a difference.

But indeed in this case it shouldn't make much of a difference to the actual value of rating.
I think that the actual saving in @Thomasdouscha database is the culprit? Like @tboothman showed in his examples only int will save the value without decimal.

**Comment by tboothman** [comment] 2021-09-04 16:23
Closing because there's no change required

**Closed by tboothman** 2021-09-04 16:23 UTC
