### ISSUE TITLE
Undefined array key 1 in Title.php preg_match

### ISSUE THREAD

**Issue by DariusIII** [tboothman/imdbphp#289] opened 2022-12-22 21:11 UTC
#### Description
I am receiving undefined array key 1 when fetching movie information. It started happening around a week ago.

Stack trace is below:

```
[2022-12-22 00:01:00] NNTmux.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at vendor/imdbphp/imdbphp/src/Imdb/Title.php:2956)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(268): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 vendor/imdbphp/imdbphp/src/Imdb/Title.php(2956): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 vendor/imdbphp/imdbphp/src/Imdb/Title.php(305): Imdb\\Title->jsonLD()
#3 Imdb\\Title->orig_title()
```

#### Movies / TV-Shows / Person
Actual movie in question is American Heart (1992): tt0103670

#### Type
Bug 

#### Code
Line 2956 in version 7.3.1:
```php
$this->jsonLD = json_decode($matches[1]);
```
I see that there were changes since last release, in master branch the line is actually 2960 now.

#### Expected Results / What do you want to do?
It should return original movie title
#### Actual Results / What is happening?
Error exception is thrown

**Comment by duck7000** [comment] 2022-12-23 18:49
In my test it works with this movie, orig_title() gives null (apparently this movie does not have a original title i guess)

If you retry does it work?
most likely the problem is that the page is not been found, hence the error about not found index key. Or the script tag is not matched/found.

Anyway there should be a check if that index exists or not to avoid the user see a error..

**Comment by duck7000** [comment] 2022-12-23 19:06
something like this would do

```
    protected function jsonLD()
    {
        if ($this->jsonLD) {
            return $this->jsonLD;
        }
        $page = $this->getPage("Title");
        if (empty($page)) {
                return array();
        }
        preg_match('#<script type="application/ld\+json">(.+?)</script>#ims', $page, $matches);
        if (isset($matches[1])) {
            return json_decode($matches[1]);
        }
    }
```

**Comment by DariusIII** [comment] 2022-12-23 20:09
I can add a check in my code, that is not an issue, but i would like to have it fixed here too.

**Comment by duck7000** [comment] 2022-12-24 10:25
Well there is nothing to fix i guess as it works here?
Can you check if the page is found and not empty?
If so then check what $matches contains?

**Comment by tboothman** [comment] 2023-02-13 18:47
Closing this because I don't get this problem with the particular title. I get the expected null return. Other methods that take data from the json+ld work (e.g. keywords) on this title too.

If you're still having the problem take a look in your cached copy of the page (cache/title.tt0103670) and see if it has `<script type="application/ld+json">` in it or not. You could also look at the html on https://www.imdb.com/title/tt0103670/ too for the same thing.

**Closed by tboothman** 2023-02-13 18:47 UTC
